fos_oauth_server_token:
        resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

ava_security_me:
    pattern:  /api/me
    defaults: { _controller: AvaSecurityBundle:Security:me }
    methods:  [GET]

ava_security_me_options:
    pattern:  /api/me
    defaults: { _controller: AvaSecurityBundle:Security:meOptions }
    methods:  [OPTIONS]

ava_test_me:
    pattern:  /usr
    defaults: { _controller: AvaSecurityBundle:Security:usr }


ava_security_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: AvaSecurityBundle:Security:login }

ava_security_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: AvaSecurityBundle:Security:loginCheck }