# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        AppBundle\Entity\User:
            id: ava_encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_db_provider:
            id: app.user.provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:    ^/secured/login$
            security: false

        secured_area:
            pattern:    ^/secured/
            form_login:
                provider: our_db_provider
                check_path: /secured/login_check
                login_path: /secured/login
            logout:
                path:   /logout
                target: /

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: our_db_provider
                check_path: ava_security_oauth_server_auth_login_check
                login_path: ava_security_oauth_server_auth_login
            anonymous: true
            context: test_connect

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true # Needed to allow access to oauth pages

    access_control:
        # You can omit this if /api can be accessed both authenticated and anonymously
        - { path: ^/oauth/v2/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/me, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], methods: [OPTIONS] }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/usr, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }