parameters:
    app.entity.user.class: AppBundle\Entity\User
    app.user.provider.class: AppBundle\Provider\UserProvider
    
services:
    app.user.manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManagerForClass
        arguments: [ "%app.entity.user.class%" ]

    app.user.repository:
        class: AppBundle\Entity\UserRepository
        factory_service: app.user.manager
        factory_method: getRepository
        arguments: ["%app.entity.user.class%"]

    app.user.provider:
        class: %app.user.provider.class%
        arguments: ["@app.user.repository"]

    ava_encoder:
        class: AppBundle\Security\AvaEncoder